# 用户表
CREATE TABLE `t_user` (
  `id`      BIGINT   NOT NULL  AUTO_INCREMENT,
  user_name VARCHAR(255) NOT NULL  DEFAULT '',
  password  VARCHAR(255) NOT NULL  DEFAULT '',
  phone     VARCHAR(255) NOT NULL  DEFAULT '',
  age       TINYINT      NOT NULL  DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = INNODB
  AUTO_INCREMENT = 1000
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin
  COMMENT ='用户表';